Repository benoitc/gunicorn, pull requests merged in 2023-05, with the labels that each got.

#2918 gthread: only read sockets when they are readable (#2917)
  gunicorn/workers/gthread.py
Labels: Improvement, Feature/Worker

#2548 Fixes #1695
  docs/source/deploy.rst
Labels: Documentation

#2649 Update SSLContext handling
  docs/source/settings.rst
  examples/example_config.py
  gunicorn/config.py
  gunicorn/sock.py
  gunicorn/workers/geventlet.py
  gunicorn/workers/ggevent.py
  gunicorn/workers/gthread.py
  gunicorn/workers/gtornado.py
  gunicorn/workers/sync.py
Labels: Feature/SSL, top priority, To Review

#2634 docs: add examples for cert-reqs
  docs/source/settings.rst
  gunicorn/config.py
Labels: Documentation, Feature/SSL

#2963 replace pkg_resources.load_entry_point
  THANKS
  gunicorn/util.py
  gunicorn/workers/geventlet.py
  gunicorn/workers/ggevent.py
  setup.py
Labels: Feature/Setup
