Repository benoitc/gunicorn, pull requests merged in 2024-08, with the labels that each got.

#2336 Fixed two bugs related to gevent + gunicorn + statsd.
  gunicorn/instrument/statsd.py
  gunicorn/workers/ggevent.py
Labels: Feature/Logging, Thirdparty/Gevent

#2688 Fix problem that may happen after interrupted chunk-encoding request
  gunicorn/http/body.py
Labels: Feature/Http

#2620 Improve access-log-format documentation section
  docs/source/settings.rst
Labels: Documentation

#2559 Typo fix for reexec related environ variables
  gunicorn/arbiter.py
Labels: Feature/Core

#2887 Fix sendfile.py example
  examples/sendfile.py
Labels: Deploy
